paritytech/command-bot

- helm/.helmignore
- helm/Chart.yaml
- helm/README.md
- helm/templates/NOTES.txt
- helm/templates/_helpers.tpl
- helm/templates/deployment.yaml
- helm/templates/hpa.yaml
- helm/templates/ingress.yaml
- helm/templates/pvc.yaml
- helm/templates/service.yaml
- helm/templates/serviceaccount.yaml
- helm/values.yaml
more information in the readme file in the helm directory
> helm chart added

- .gitlab-ci.yml
Resolves #11.
Resolves https://github.com/paritytech/ci_cd/issues/175.
> Configure proper GitLab mirroring and enable CI on PRs

- src/webhook.ts
closes https://github.com/paritytech/try-runtime-bot/issues/26
> Everything should be release mode, non-negotiable

- src/utils.ts
As showcased in https://github.com/paritytech/polkadot/pull/4772#issuecomment-1028595106 the CLI is apparently using the `--uri` argument nowadays, [where previously](https://github.com/paritytech/polkadot/pull/4772#issuecomment-1028595106) we were only considering `--url`.
Given that we want to avoid breaking the bot when the CLI arguments arbitrarily change, this PR attempts to improve the argument parsing so that:
- Any argument with URI-ish prefix (`*://*`, e.g. `ws://polkadot`) is treated as a node address
- All arguments in the forms `--foo`, `-foo`, `-foo=` and `--foo=` are considered instead of only the hardcoded `--url`
> Improve argument parsing

- scripts/generateDockerfile
- src/executor.ts
- src/github.ts
- src/utils.ts
- src/webhook.ts
> Fix the build and remaining errors which appeared on polkadot#4772

- README.md
- env/bot.example.cjs
- src/api.ts
> Update the documentation

- README.md
- src/api.ts
- src/bot.ts
- src/core.ts
> Fix environment variables parsing

- .gitlab-ci.yml
- README.md
- src/api.ts
- src/bot.ts
- src/core.ts
- src/github.ts
- src/gitlab.ts
- src/task.ts
- src/types.ts
> Save information on PR contributor and upstream repositories

- src/core.ts
:exclamation: Do not merge before https://github.com/paritytech/ci_cd/issues/431 is done
Blocked by https://github.com/paritytech/ci_cd/issues/431
closes #65
> Update CI tag for bench-bot command

- src/gitlab.ts
> Handle leftover files from previous runs in the same shell executor

- .github/dependabot.yml
- package.json
- yarn.lock
We're not interested in typings for Node 17+ since we're using Node 16 in this project
> Pin to Node.js 16

- src/core.ts
:warning: merge it after https://github.com/paritytech/pipeline-scripts/pull/64
close #90
close #83
> Move try-runtime-bot's hardcoded configuration to pipeline scripts

- src/core.ts
just following the guidance from https://github.com/paritytech/command-bot/issues/93
> add fmt command

- src/__snapshots__/gitlab.spec.ts.snap
- src/gitlab.spec.ts
- src/gitlab.ts
- src/task.ts
- src/types.ts
+ make the pipeline scripts REF to be overridable, 
+ add more logs to investigate sporadic cancellations
> make the pipeline scripts REF to be overridable, and add more logs to investigate sporadic cancellations

- .gitlab-ci.yml
cc https://github.com/paritytech/ci_cd/issues/544
> [ci] new runner for deploy

- .gitlab-ci.yml
cc https://github.com/paritytech/ci_cd/issues/544
> [ci] remove environment

- .env.example.cjs
- README.md
- helm/values-parity-prod.yaml
- helm/values-parity-stg.yaml
- package.json
- src/api.ts
- src/config.ts
- src/db.ts
- src/setup.ts
- src/task.ts
- src/types.ts
- yarn.lock
Closes https://github.com/paritytech/command-bot/issues/183
- Matrix isn't used, so clean up
- AccessDB and /access exists in limbo, never used anywhere 
- Keep ApiTask for future, output the result of task to a server logs
> cleaned up matrix & accessDb

- src/bot/setupEvent.ts
- src/metrics.ts
instead of creating separate metrics, combine them by label `type`
easier to create a panel by type and manage labels
> a better way to form total metrics for commands

- src/command-configs/fetchCommandsConfiguration.ts
fix: https://github.com/paritytech/command-bot/issues/198
> rm old latest.html & handle exception

- src/command-configs/help/parts/hero.pug
- src/command-configs/renderHelpPage.ts
> Cosmetic changes of the help page text

- src/command-configs/help/parts/navigation.pug
- src/command-configs/help/parts/styles.pug
> fix navigation links

- helm/values-parity-prod.yaml
- helm/values-parity-stg.yaml
- src/command-configs/help/parts/commands.pug
To be in sync with what monorepo CI uses right now.
> Bump `ci-unified` to `1.73.0`

- helm/values-parity-prod.yaml
- helm/values-parity-stg.yaml
- helm/values.yaml
New image has updated rust nightly
> Update CI image for command bot

- helm/values-parity-prod.yaml
- helm/values-parity-stg.yaml
- helm/values.yaml
Merge and deploy after https://github.com/paritytech/polkadot-sdk/pull/2545
> Update rust image 1.74

- .gitlab-ci.yml
Addresses https://github.com/paritytech/ci_cd/issues/916
> CI Update Vault auth
