paritytech/command-bot

src/executor.ts
src/webhook.ts

The problem of #42 might be due to us missing some output due to only capturing `stdout` but not `stderr`.
This PR implements capturing both `stdout` and `stderr` when we run the try-runtime-cli command.
might fix #42

Capture all output streams for try-runtime-cli

---

.env.example.cjs
.gitlab-ci.yml
README.md
helm/values.yaml
package.json
scripts/generateDockerfile
src/api.ts
src/bot.ts
src/core.ts
src/github.ts
src/gitlab.ts
src/logger.ts
src/main.ts
src/setup.ts
src/shell.ts
src/task.ts
src/types.ts
src/utils.ts
yarn.lock

This PR refactors the code base in order to enable the execution arbitrary commands through GitLab CI instead of having the bot be hardcoded to executing the try-runtime-cli directly in the host. In-depth motivation for this design was given in https://github.com/paritytech/opstooling/issues/105.
Example usage is given at https://github.com/paritytech/polkadot/pull/5478#issuecomment-1120435275.
After this PR is deployed we should rebrand this repository as `command-bot` and update the external documentation, such as https://gitlab.parity.io/groups/parity/opstooling/-/wikis, to reflect the new name.
closes https://github.com/paritytech/opstooling/issues/105
related to https://github.com/paritytech/devops/issues/1589
blocked by https://github.com/paritytech/devops/issues/1631 for …

command-bot

---

.github/dependabot.yml

There's little point in creating PRs when new major versions come out, as it usually will include breaking changes.   Also, keeping versions aligned between our internal dependencies is probably a better practice than having all latest major versions of dependencies deployed to all services.
Signed-off-by: Yuri Volkov <0@mcornholio.ru>

Excluding semver-major from dependabot

---

src/bot/events/onIssueCommentCreated.ts
src/bot/parse/ParsedCommand.ts
src/bot/parse/parsePullRequestBotCommandLine.spec.ts
src/bot/parse/parsePullRequestBotCommandLine.ts
src/bot/setupEvent.ts
src/bot/types.ts
src/command-configs/renderHelpPage.pug
src/command-configs/renderHelpPage.ts
src/github.ts
src/types.ts
test/github-non-pipeline-cases.spec.ts

Fixes: #158 
`bot clean` with 👀 and 👍 reaction on start and finish accordingly, cuz it could take time to do that, and it needs to be "responsive" and more transparent of what is going on.
I was trying to set "common" way to react on commands, but whole PR looked over😵‍💫smiled, so keeping only for `bot clean`  where it makes more sense

add clean command

---

.gitlab-ci.yml
deploy-stg.sh
src/bot/parse/parsePullRequestBotCommandLine.spec.ts
src/bot/parse/parsePullRequestBotCommandLine.ts
src/bot/setupEvent.ts
src/command-configs/renderHelpPage.pug
src/command-configs/renderHelpPage.ts
src/schema/schema.cmd.json
src/test/github-ignore-comands.spec.ts
src/test/github-non-pipeline-cases.spec.ts
src/test/setup/bot.ts
src/test/setup/integration.setupAfterEnv.ts

Closes #170
In order to skip showing the "sample" example introduced an "exclude" flag to skip from docs. 
We could simply delete "sample" and there's no problem but i found it useful often to check quickly that gitlab jobs with parameters work, so would prefer to keep.
- Docs: 
- support "example" field from **type_rule**
- skip rendering a table with **args**, if there's no args (also make it not required)
- make help/clean so they go as first basic commands in docs
- add "excluded" to schema, so some commands could be skipped in docs

add "excluded" to schema +  add help/clean to docs

---

src/gitlab.ts
src/task.ts
src/test/github-job-cancellation.spec.ts
src/utils.ts

Added more logging + increased delay after creating a fresh branch

---

src/bot/events/onIssueCommentCreated.ts
src/bot/parse/isOptionalArgsCommand.spec.ts
src/bot/parse/isOptionalArgsCommand.ts
src/bot/parse/parsePullRequestBotCommandLine.spec.ts
src/bot/parse/parsePullRequestBotCommandLine.ts
src/test/github-non-pipeline-cases.spec.ts

Closes #171 
Testing: 
- https://github.com/mak-parity-org2/substrate/pull/1 `bot bench-all` has no args
- https://github.com/mak-parity-org2/polkadot/pull/1 `bot bench-all` requires ` $ polkadot` or other network
Also added check for repository, so you can't run wrong command in wrong repo, like [sample](https://github.com/paritytech/command-bot-scripts/blob/main/commands/sample/sample.cmd.json#L16) is polkadot only, and if you run it in scope of substrate you'll get this error

enhanced args validation making it optional per preset

---

src/gitlab.ts
src/utils.spec.ts
src/utils.ts

Closes https://github.com/paritytech/command-bot/issues/166
the issue was the fact that when we push a .gitlab-ci.yml with a command script, it tried to get a pipeline very soon after a push. The problem doesn't reproduce on small repositories, only on prod on huge repos, when the pipeline starts with slight more delay. So 
1st. - move the preventive delay right before the pipeline + 
2nd. - wrap pipeline query into retriable

wrap pipeline query into retriable

---

.gitlab-ci.yml

Last deploy 300s [were not enough ](https://gitlab.parity.io/parity/mirrors/command-bot/-/jobs/2667847) (it took too long to download the image to host). PR increases timeout

[ci] Increase deploy timeout

---

README.md
helm/values-parity-prod.yaml
helm/values-parity-stg.yaml
src/api.ts
src/bot/events/onIssueCommentCreated.ts
src/command-configs/help/parts/commands.pug
src/command-configs/help/parts/navigation.pug
src/main.ts
src/schema/schema.cmd.json
src/setup.ts
src/types.ts

make Command's job CI image configurable

---

src/command-configs/help/parts/commands_preset.pug

Use labels for repos in the help page

---

src/bot/events/onIssueCommentCreated.ts
src/bot/setupEvent.ts
src/bot/types.ts

Closes https://github.com/paritytech/command-bot/issues/223

fix check membership & skip events

---

src/bot/events/handlers/EventHandler.ts
src/bot/events/handlers/cancelHandler.ts
src/bot/events/handlers/cleanHandler.ts
src/bot/events/handlers/genericHandler.ts
src/bot/events/handlers/helpHandler.ts
src/bot/events/handlers/skipHandler.ts
src/bot/events/onIssueCommentCreated.ts
src/bot/parse/guessCommand.ts
src/bot/types.ts
src/commander/commander.ts
src/utils.ts

To simplify the onIssueCommentCreated.ts handler I have split it into more granular parts
I wanted to store handlers in different files so it's easier to navigate

split event handlers

---

src/command-configs/help/parts/commands_preset.pug
src/command-configs/help/parts/navigation.pug

- Fix #231 
- Remove default from the nav list, as root command link anyway leads to the same place

Mak fix docs

---

src/bot/parse/parsePullRequestBotCommandLine.namedArgs.spec.ts
src/bot/parse/parsePullRequestBotCommandLine.spec.ts
src/command-configs/__mocks__/fetchCommandsConfiguration.ts
src/command-configs/renderHelpPage.ts
src/command-configs/utils.spec.ts
src/command-configs/utils.ts
src/commander/commander.ts
src/test/github-non-pipeline-cases.spec.ts
src/test/github-positive-scenario.spec.ts

Closes #233 
Tested locally 
Also added validation of commands & subcommands in scope of repo - will fail with related message

Add argument & command validation in scope of repo

---

package.json
src/bot/parse/parsePullRequestBotCommandLine.namedArgs.spec.ts
src/commander/commander.ts
src/test/github-ignore-comands.spec.ts
src/test/github-non-pipeline-cases.spec.ts
yarn.lock

add merge/rebase response; fix crashing app on wrong argument in root
I'm curious how long do they store these assets in GitHub?

add merge/rebase response; fix crashing app on wrong argument in root

---

src/api.ts
src/bot/events/handlers/genericHandler.ts
src/gitlab.ts
src/gitlab/createCiConfig.ts
src/schema/schema.cmd.json
src/task.ts
src/test/github-job-failure.spec.ts
src/test/github-positive-scenario.spec.ts
src/test/setup/integration.setupAfterEnv.ts

Some jobs would require an increased expected timeout to run. The sync for example
sync command: https://github.com/paritytech/command-bot-scripts/pull/53

support setting a timeout for a job

---

src/bot/parse/guessCommand.spec.ts
src/bot/parse/parsePullRequestBotCommandLine.namedArgs.spec.ts
src/command-configs/__mocks__/fetchCommandsConfiguration.ts

Changes related to #242.
Removes arguments for benchmarks for the following:
- `asset-hub-kusama` and `asset-hub-polkadot`
- `bridge-hub-kusama` and `bridge-hub-polkadot`
- `collectives-polkadot`
- `glutton-kusama`
Adds arguments for 
- `collectives-westend`
- `glutton-westend`
To be merged after [this PR](https://github.com/paritytech/polkadot-sdk/pull/1737) in `polkadot-sdk` and along with [this PR](https://github.com/paritytech/command-bot-scripts/pull/52) in `command-bot-scripts`

Remove system parachain native runtimes after polkadot-sdk #1737

---

helm/values-parity-prod.yaml
helm/values-parity-stg.yaml
helm/values.yaml
src/command-configs/help/parts/commands.pug

A usual followup after bumping the image  in the `polkadot-sdk` CI.

Bump `ci-unified` to `v20240103`

---

helm/values-parity-prod.yaml
helm/values-parity-stg.yaml
helm/values.yaml
src/command-configs/help/parts/commands.pug

Usual upgrade chore as per https://github.com/paritytech/ci_cd/issues/926.

`ci-unified` with Rust 1.75

---

helm/Chart.yaml
helm/values-parity-prod.yaml
helm/values-parity-stg.yaml
helm/values.yaml

Part of https://github.com/paritytech/devops/issues/3323

Move charts to its application repos

---

helm/values-parity-prod.yaml
helm/values-parity-stg.yaml
helm/values.yaml

cc https://github.com/paritytech/ci_cd/issues/1035
should be deployed after https://github.com/paritytech/polkadot-sdk/pull/5676

Use rust 1.81
